name: map_of_canada
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_pmtiles: ^1.0.4
  pmtiles: ^1.3.0
  supabase_flutter: ^2.6.0
  vector_map_tiles_pmtiles: ^1.4.0
  vector_tile_renderer: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
